### ISSUE TITLE
Change License to LGPL

### ISSUE THREAD

**Issue by mont3z** [shuwang127/SRCNN_Cpp#1]
Hi,

I'm thinking on writing a ffmpeg filter using your code. Although GPL would be to restrictive for this. Would you consider changing the license to LGPL 2.1?
 
http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html
https://www.ffmpeg.org/legal.html

Thanks,
Montez

**Comment by shuwang127** [comment]
OK, I will change the license.
